/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekranlar;

import Client.Client;
import Message.Message;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author MONSTER
 */
public class Chat extends javax.swing.JFrame {

    public DefaultListModel dlm = new DefaultListModel();

    /**
     * Creates new form rooms
     */
    public Chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Chat_textArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        chat_send = new javax.swing.JButton();
        chat_sendDocument = new javax.swing.JButton();
        chat_chatText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        chat_clientList = new javax.swing.JList<>();
        chat_refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        roomlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Chat_textArea.setColumns(20);
        Chat_textArea.setRows(5);
        jScrollPane1.setViewportView(Chat_textArea);

        jLabel1.setText("Grup Sohbet Ekranı");

        chat_send.setText("Gönder");
        chat_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_sendActionPerformed(evt);
            }
        });

        chat_sendDocument.setText("Dosya");
        chat_sendDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_sendDocumentActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(chat_clientList);

        chat_refresh.setText("Yenile");
        chat_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_refreshActionPerformed(evt);
            }
        });

        jLabel2.setText("Clients");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chat_chatText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(chat_sendDocument)
                        .addGap(18, 18, 18)
                        .addComponent(chat_send))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(chat_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(roomlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chat_send, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chat_sendDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chat_chatText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chat_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chat_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_refreshActionPerformed
        System.out.println("refresh clickeddd");
        Message refreshMessage = new Message(Message.Message_Type.REFRESH);
        refreshMessage.content = roomlbl.getText().toLowerCase();
        System.out.println("refresh message.content : " + refreshMessage.content);
        Client.SendServer(refreshMessage);
    }//GEN-LAST:event_chat_refreshActionPerformed

    private void chat_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_sendActionPerformed
        if (chat_chatText.getText() != null) {
            Message msg = new Message(Message.Message_Type.TEXT);
            msg.content = chat_chatText.getText();
            Client.SendServer(msg);
        }
        chat_chatText.setText("");
    }//GEN-LAST:event_chat_sendActionPerformed

    private void chat_sendDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_sendDocumentActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int selection = fileChooser.showOpenDialog(this);
        
        File file = null;
        // keep selected file from chooser in file variable
        if (selection == JFileChooser.APPROVE_OPTION)
            file = fileChooser.getSelectedFile();
        
        byte fileContent[] = new byte[(int)file.length()];
        try {
            BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file));
            bis.read(fileContent, 0, fileContent.length);
            Message fileMSG = new Message(Message.Message_Type.ROOM_FILE);
            fileMSG.fileContent = fileContent;
            fileMSG.content = file.getName(); // msg.content == file name
            Client.SendServer(fileMSG);
            System.out.println("Sended file path: "+file.getAbsolutePath());
            
            // notifying to message sended by who
            String sender = Login.menu.jLabel1.getText().substring(3, Login.menu.jLabel1.getText().length()-1);
            Message notifyFileMSG = new Message(Message.Message_Type.ROOM_FILE_NOTIFY);
            notifyFileMSG.content = sender.toUpperCase() + ": " + file.getName() + " shared";
            Client.SendServer(notifyFileMSG);
            
        } catch (FileNotFoundException ex) {
            System.out.println("File not found.. "+ex);
        } catch (IOException ex) {
            System.out.println("File read exception.."+ex);
        }
    }//GEN-LAST:event_chat_sendDocumentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Chat_textArea;
    private javax.swing.JTextField chat_chatText;
    public javax.swing.JList<String> chat_clientList;
    private javax.swing.JButton chat_refresh;
    private javax.swing.JButton chat_send;
    private javax.swing.JButton chat_sendDocument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel roomlbl;
    // End of variables declaration//GEN-END:variables
}
