/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekranlar;

import Client.Client;
import Message.Message;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MONSTER
 */
public class Menu extends javax.swing.JFrame {

    public DefaultListModel dlm = new DefaultListModel();   // to holding clients
    public DefaultListModel dlm2 = new DefaultListModel();  // to holding rooms
    public Chat chat = new Chat();
    public P2PChat singleChat = new P2PChat();

    /**
     * Creates new form roomchat
     */
    public Menu() {
        initComponents();
        menu_list.setModel(dlm);
        menu_roomList.setModel(dlm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        menu_roomList = new javax.swing.JList<>();
        menu_join = new javax.swing.JButton();
        oda_name = new javax.swing.JLabel();
        menu_createTxt = new javax.swing.JTextField();
        menu_create = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        menu_list = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        menu_startChat = new javax.swing.JButton();
        menu_showClients = new javax.swing.JButton();
        menu_showRooms = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(menu_roomList);

        menu_join.setText("Odaya Katıl");
        menu_join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_joinActionPerformed(evt);
            }
        });

        oda_name.setText("Oda İsmi :");

        menu_create.setText("Odayı Kur");
        menu_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_createActionPerformed(evt);
            }
        });

        jLabel2.setText("Odalar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Yeni Proje Odası Oluşturmak İstiyorsanız");

        jScrollPane3.setViewportView(menu_list);

        jLabel4.setText("Clients");

        menu_startChat.setText("Sohbet Başlat");
        menu_startChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_startChatActionPerformed(evt);
            }
        });

        menu_showClients.setText("Listele");
        menu_showClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_showClientsActionPerformed(evt);
            }
        });

        menu_showRooms.setText("Listele");
        menu_showRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_showRoomsActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oda_name, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_createTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menu_create, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menu_join, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menu_showRooms, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menu_showClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(menu_startChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_createTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oda_name)
                    .addComponent(menu_create))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(menu_showClients)
                    .addComponent(menu_showRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_join)
                    .addComponent(menu_startChat))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_joinActionPerformed
        Message msg = new Message(Message.Message_Type.JOIN_ROOM);
        msg.content = (String) menu_roomList.getSelectedValue();
        System.out.println("choosen room name: " + msg.content);
        Client.SendServer(msg);

    }//GEN-LAST:event_menu_joinActionPerformed

    private void menu_startChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_startChatActionPerformed
        Message msg = new Message(Message.Message_Type.START_CHAT);
        msg.content = (String) menu_list.getSelectedValue();
        msg.senderName = jLabel1.getText().substring(3, jLabel1.getText().length() - 1);
        System.out.println("msg.senderName: " + msg.senderName);
        Client.SendServer(msg);
        JOptionPane.showMessageDialog(this, "Chat response waiting...");
    }//GEN-LAST:event_menu_startChatActionPerformed

    private void menu_showClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_showClientsActionPerformed
        System.out.println("SHOW CLIENTS BUTTON GIRDIMM");
        Message msg = new Message(Message.Message_Type.LIST);
        Client.SendServer(msg);
    }//GEN-LAST:event_menu_showClientsActionPerformed

    private void menu_showRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_showRoomsActionPerformed
        Message msg = new Message(Message.Message_Type.ROOM_LIST);
        Client.SendServer(msg);
    }//GEN-LAST:event_menu_showRoomsActionPerformed

    private void menu_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_createActionPerformed
        if (menu_createTxt.getText().equals(null) || menu_createTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a room name before creation !!");
            return;
        }
        Message msg = new Message(Message.Message_Type.ROOM_NAME);
        msg.content = menu_createTxt.getText();
        Client.SendServer(msg);
    }//GEN-LAST:event_menu_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton menu_create;
    private javax.swing.JTextField menu_createTxt;
    private javax.swing.JButton menu_join;
    private javax.swing.JList<String> menu_list;
    private javax.swing.JList<String> menu_roomList;
    private javax.swing.JButton menu_showClients;
    private javax.swing.JButton menu_showRooms;
    private javax.swing.JButton menu_startChat;
    private javax.swing.JLabel oda_name;
    // End of variables declaration//GEN-END:variables
}
